# Build transform for the gasmax.fun deploy: run as `perl -0p deploy.pl index.html > site/index.html`
# Delimiters are `#` so that `|` inside JavaScript never becomes a regex alternative.
# 1. drop the embedded base64 model (the host serves assets/gasmax-lite.glb instead)
s#<script type="text/plain" id="gasmaxModel">.*?</script>\n##s;
# 2. load the same-origin copy first; the published URL is only a fallback
s#    /\* 1\. the merged model at its published URL \(needs CORS \+ a network that allows it\) \*/\n    try \{ return await loadUrl\(MODEL_URL\); \} catch \(e\) \{ console\.warn\('GASMAX: remote model unavailable, trying the local copy', e && e\.message\); \}\n    /\* 2\. a same-origin slim copy next to the page \*/\n    try \{ return await loadUrl\('assets/gasmax-lite\.glb'\); \} catch \(e\) \{ console\.warn\('GASMAX: local copy unavailable, using the embedded copy'\); \}#    /* 1. the slim copy served next to the page */\n    try { return await loadUrl('assets/gasmax-lite.glb'); } catch (e) { console.warn('GASMAX: local copy unavailable, trying the published URL', e && e.message); }\n    /* 2. the merged model at its published URL (needs CORS on that host) */\n    try { return await loadUrl(MODEL_URL); } catch (e) { console.warn('GASMAX: remote model unavailable'); }#;
# 3. full document skeleton, canonical URL, social preview, favicon, preload hints
s#\A\x{FEFF}?<title>\$GASMAX Pit Stop</title>\r?\n<meta name="viewport" content="width=device-width, initial-scale=1">\r?\n<meta name="description" content="([^"]*)">#<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>GASMAX Pit Stop</title>\n<meta name="description" content="$1">\n<link rel="canonical" href="https://gasmax.fun/">\n<meta name="theme-color" content="\#050807">\n<link rel="icon" href="/favicon.svg" type="image/svg+xml">\n<link rel="preload" href="assets/gasmax-lite.glb" as="fetch" crossorigin="anonymous">\n<link rel="modulepreload" href="https://cdn.jsdelivr.net/npm/three\@0.184.0/+esm">\n<meta property="og:type" content="website">\n<meta property="og:site_name" content="GASMAX">\n<meta property="og:title" content="GASMAX Pit Stop">\n<meta property="og:description" content="$1">\n<meta property="og:url" content="https://gasmax.fun/">\n<meta property="og:image" content="https://gasmax.fun/og-image.png">\n<meta property="og:image:width" content="1200">\n<meta property="og:image:height" content="630">\n<meta name="twitter:card" content="summary_large_image">\n<meta name="twitter:site" content="\@GasMaxEVM">\n<meta name="twitter:title" content="GASMAX Pit Stop">\n<meta name="twitter:description" content="$1">\n<meta name="twitter:image" content="https://gasmax.fun/og-image.png">#;
s#\n<a class="skip" href="\#main">Skip to content</a>#\n</head>\n<body>\n<a class="skip" href="\#main">Skip to content</a>#;
s#\z#</body>\n</html>\n#;
