# Launch config: one contract address drives every link. Delimiter is # so `||` in JS is safe.
s#const CA = '0x0000000000000000000000000000000000000000';#/* ---------- LAUNCH CONFIG: paste the contract address into `ca` at launch; every link below derives from it */\nconst LAUNCH = { ca: '', chain: 'base' };\nconst CHAINS = {\n  base: { name: 'Base', explorer: 'https://basescan.org/token/', dex: 'https://dexscreener.com/base/', swap: 'https://app.uniswap.org/swap?chain=base\&outputCurrency=' },\n  ethereum: { name: 'Ethereum', explorer: 'https://etherscan.io/token/', dex: 'https://dexscreener.com/ethereum/', swap: 'https://app.uniswap.org/swap?chain=mainnet\&outputCurrency=' },\n};\nconst CA = LAUNCH.ca;\nconst LIVE = /^0x[0-9a-fA-F]{40}\$/.test(CA);\nconst CHAIN = CHAINS[LAUNCH.chain] || CHAINS.base;#;
s#\$\$\('\.copyCa'\)\.forEach\(b => b\.addEventListener\('click', async \(\) => \{ try \{ await navigator\.clipboard\.writeText\(CA\); \} catch \(e\) \{\} toast\('Placeholder address copied\. Set the real contract before launch\.'\); \}\)\);#\$\$('.ca b').forEach(b => { b.textContent = LIVE ? CA.slice(0, 6) + '…' + CA.slice(-4) : 'drops at launch'; });\n\$\$('.copyCa').forEach(b => b.addEventListener('click', async () => {\n  if (!LIVE) { toast('The contract address drops at launch. Follow \@GasMaxEVM on X.'); return; }\n  try { await navigator.clipboard.writeText(CA); } catch (e) {}\n  toast('Contract address copied');\n}));\nconst soon = (msg) => (e) => { e.preventDefault(); toast(msg); };\n\$\$('a[data-todo]').forEach(a => {\n  const t = a.dataset.todo || '';\n  const wire = (url, msg) => { if (LIVE) { a.href = url; a.target = '_blank'; a.rel = 'noopener'; } else a.addEventListener('click', soon(msg)); };\n  if (t.startsWith('link to DEX')) wire(CHAIN.swap + CA, 'Buying opens at launch. Follow \@GasMaxEVM on X for the contract.');\n  else if (t === 'Dexscreener link') wire(CHAIN.dex + CA, 'The chart goes live with the contract at launch.');\n  else if (t === 'contract explorer link') wire(CHAIN.explorer + CA, 'The contract address drops at launch.');\n});#;
# footer: no docs or Telegram
s#        <a href="\#" data-todo="docs link">Docs</a>\n##;
s#        <a href="\#" data-todo="Telegram link">Telegram</a>\n##;
# footer pill label
s#<span>CA · <b id="caShort">placeholder until launch</b></span>#<span>CA · <b id="caShort">drops at launch</b></span>#;
# hero pill label
s#<span>CA: <b>0x7a3…e1b5c \(placeholder until launch\)</b></span>#<span>CA: <b>drops at launch</b></span>#;
