# Smooth loading: composited glow, staged 3D start-up, paused background work. Delimiter ~.
# CSS: no per-frame transitions, spill on a transform, overlay fade composited
s~\.sl-fill\{position:absolute;top:0;bottom:0;left:0;width:4%;border-radius:4px;background:linear-gradient\(180deg,\#5CFF9C,\#00FF66 55%,\#00C853\);box-shadow:0 0 12px rgba\(0,255,102,\.7\),0 0 30px rgba\(0,255,102,\.35\);transition:width \.3s ease-out\}~.sl-fill{position:absolute;top:0;bottom:0;left:0;width:4%;border-radius:4px;background:linear-gradient(180deg,\#5CFF9C,\#00FF66 55%,\#00C853);box-shadow:0 0 12px rgba(0,255,102,.7),0 0 30px rgba(0,255,102,.35)}~;
s~\.sl-spill\{position:absolute;left:3px;top:100%;height:70px;width:4%;margin-top:-4px;background:radial-gradient\(ellipse 60% 100% at 50% 0,rgba\(0,255,102,\.3\),transparent 70%\);filter:blur\(10px\);pointer-events:none;transition:width \.3s ease-out\}~.sl-spill{position:absolute;left:3px;top:100%;height:70px;width:calc(100% - 6px);transform:scaleX(.04);transform-origin:left center;will-change:transform;margin-top:-4px;background:radial-gradient(ellipse 60% 100% at 50% 0,rgba(0,255,102,.3),transparent 70%);filter:blur(10px);pointer-events:none}~;
s~transition:opacity \.7s ease,visibility \.7s;font-family:var\(--body\)\}~transition:opacity .7s ease,visibility .7s;will-change:opacity;font-family:var(--body)}~;
# controller: transform-based paint, finish callbacks fired after the fade
s~  const paint = \(\) => \{ const w = \(shown \* 100\)\.toFixed\(2\) \+ '%'; fill\.style\.width = w; spill\.style\.width = w; pct\.textContent = Math\.round\(shown \* 100\) \+ '%'; \};~  const finishCbs = [];\n  const paint = () => { fill.style.width = (shown * 100).toFixed(2) + '%'; spill.style.transform = 'scaleX(' + shown.toFixed(4) + ')'; pct.textContent = Math.round(shown * 100) + '%'; };~;
s~setTimeout\(\(\) => el\.remove\(\), 900\); \}, 260\); \};~setTimeout(() => { el.remove(); finishCbs.splice(0).forEach(cb => { try { cb(); } catch (e) {} }); }, 900); }, 260); };~;
s~    done\(\) \{ complete = true; \},\n    _debug:~    done() { complete = true; },\n    onFinish(cb) { if (finished \&\& !document.getElementById('siteLoader')) cb(); else finishCbs.push(cb); },\n    _debug:~;
# background blobs: do not draw while the loading screen is up
s~  function frame\(t\) \{ if \(t - last > 40\) \{ draw\(t\); last = t; \} requestAnimationFrame\(frame\); \}~  function frame(t) { if (t - last > 40 \&\& !document.documentElement.classList.contains('is-loading')) { draw(t); last = t; } requestAnimationFrame(frame); }~;
# 3D module: normals in slices, shaders compiled async, one frame for the fade-in, loop starts after the overlay is gone
s~const pumpLights = \[\];\nroot\.traverse\(o => \{\n  if \(!o\.isMesh\) return;\n  if \(!o\.geometry\.getAttribute\('normal'\)\) o\.geometry\.computeVertexNormals\(\);~const pumpLights = [];\nconst needNormals = [];\nroot.traverse(o => {\n  if (!o.isMesh) return;\n  if (!o.geometry.getAttribute('normal')) needNormals.push(o.geometry);~;
s~  o\.castShadow = true; o\.receiveShadow = true;\n\}\);\nlet modelLight = null;~  o.castShadow = true; o.receiveShadow = true;\n});\n/* normals one mesh at a time, yielding between meshes so the loading bar keeps animating */\nfor (let i = 0; i < needNormals.length; i++) { needNormals[i].computeVertexNormals(); setProgress(0.9 + 0.05 * (i / needNormals.length), 'Building scene'); await new Promise(r => setTimeout(r, 0)); }\nlet modelLight = null;~;
s~requestAnimationFrame\(frame\);\nrequestAnimationFrame\(\(\) => requestAnimationFrame\(\(\) => \{ if \(window\.__loading\) window\.__loading\.done\(\); \}\)\);\nsetTimeout\(\(\) => \{ if \(window\.__loading\) window\.__loading\.done\(\); \}, 1500\);\nwindow\.__rig = \{~/* compile shaders without blocking where supported, draw the first frame for the fade-in, then let the loading screen finish; the loop starts once the overlay is gone */\ntry { if (renderer.compileAsync) await renderer.compileAsync(scene, camera); } catch (e) {}\nstep(performance.now());\nlet loopStarted = false;\nconst startLoop = () => { if (loopStarted) return; loopStarted = true; last = performance.now(); requestAnimationFrame(frame); };\nif (window.__loading \&\& window.__loading.onFinish) { window.__loading.onFinish(startLoop); window.__loading.done(); } else startLoop();\nsetTimeout(startLoop, 8000);\nwindow.__rig = {~;
